---
# Node exporter configuration
collectors:
  enabled: all
  disabled:
    - mdadm  # Disable if not needed
    - wifi   # Disable if not needed
  filesystem:
    ignored-mount-points: "^/(dev|proc|sys|var/lib/docker/.+)($|/)"
    ignored-fs-types: "^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$" 