version: '3.8'

services:
  rmw_deployment:
    image: steelduck1/rmw-deployment:latest
    ports:
      - "8080:8080"
    environment:
      - DEPLOY_API_KEY=your_deployment_api_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - rmw-network

  rmw_frontend:
    image: steelduck1/rmw-frontend:latest
    ports:
      - "80:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - rmw-network

  rmw_backend:
    image: steelduck1/rmw-backend:latest
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - rmw-network
    depends_on:
      - rmw_database

  rmw_database:
    image: steelduck1/rmw-database:latest
    ports:
      - "8001:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - rmw_database_data:/app/data
    networks:
      - rmw-network

networks:
  rmw-network:
    driver: overlay

volumes:
  rmw_database_data:
