version: "3.8"

services:
  Deployment:
    image: steelduck1/RMW-Deployment:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Zorg dat de container de Docker daemon kan aansturen
    environment:
      - DEPLOY_API_KEY=Belastingdienst321!  # Stel hier jouw gewenste API key in

  Backend:
    image: steelduck1/RMW-Backend:latest
    ports:
      - "9100:9000"
    deploy:
      replicas: 2  # Use 2 replicas for zero downtime
      update_config:
        parallelism: 1
        delay: 5s  # Faster delay between updates
        order: start-first  # Start new container before stopping the old one
      restart_policy:
        condition: any

  Database:
    image: steelduck1/RMW-Database:latest
    ports:
      - "9200:9200"
    volumes:
      - db-data:/app/db  # Persistent volume for database storage
    deploy:
      replicas: 1  # Only one instance for the database to avoid conflicts
      restart_policy:
        condition: any

volumes:
  db-data:  # Define the volume for database persistence
