name: Measure During-deploy Pings (2 minutes)

on:
  push:
    branches: ["main"]

jobs:
  measure-during:
    runs-on: ubuntu-latest
    steps:
      - name: Measure API pings for 2 minutes
        run: |
          #!/bin/bash
          set -e
          echo "Starting continuous pings for 2 minutes..."
          
          # Definieer de API-URL
          PING_URL="http://kanslozeknapen.eu:9001/calculate?operation=add&x=10&y=12"
          
          # Starttijd met hoge precisie
          start=$(date +%s.%N)
          sum=0
          count=0
          # Maak een array om de ping-resultaten op te slaan
          ping_results=()
          
          # Loop zolang 120 seconden niet zijn verstreken
          while true; do
            now=$(date +%s.%N)
            elapsed=$(echo "$now - $start" | bc -l)
            if (( $(echo "$elapsed >= 120" | bc -l) )); then
              break
            fi
            
            # Voer de ping uit met curl en vang zowel de respons als de ping-tijd op.
            # De respons wordt standaard uitgeprint, dus we verwijderen niet meer met -o /dev/null.
            # De -w "\n%{time_total}" zorgt ervoor dat de totale tijd op een nieuwe regel komt.
            output=$(curl -s -w "\n%{time_total}" "$PING_URL")
            
            # Splits de output: de laatste regel is de ping-tijd, de rest is de respons.
            ping=$(echo "$output" | tail -n1)
            result=$(echo "$output" | sed '$d')
            
            ping_results+=("$ping")
            sum=$(echo "$sum + $ping" | bc -l)
            count=$((count + 1))
            echo "Ping $count: $ping sec (elapsed: $elapsed sec) result: $result"
            sleep 0.2
          done
          
          # Bereken het gemiddelde
          avg=$(echo "scale=4; $sum / $count" | bc -l)
          echo ""
          echo "===== Ping Results ====="
          echo "Total pings: $count"
          echo "Average ping time: $avg sec"
          echo "Top 3 longest pings:"
          # Sorteer de array afdalend en selecteer de top 3
          printf "%s\n" "${ping_results[@]}" | sort -nr | head -n 3
