version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  monitor-net:

services:
  prometheus:
    image: prom/prometheus:v2.36.2
    ports:
      - 9090:9090
    networks:
      - monitor-net
    deploy:
      restart_policy:
        condition: on-failure

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - 8081:8080
    networks:
      - monitor-net
    deploy:
      mode: global 