name: Build and Deploy Monitoring Stack

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'RMW-Monitoring/**'
      - '.github/workflows/BuildAndDeploy_Monitoring.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.head_ref == 'Monitoring')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: steelduck1/rmw-monitoring
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./RMW-Monitoring
          push: true
          tags: steelduck1/rmw-monitoring:latest
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Trigger redeploy
        id: redeploy
        run: |
          echo "Triggering redeploy..."
          REDEPLOY_URL="http://188.166.89.152:8080/redeploy?api_key=${DEPLOY_API_KEY}&service=monitoring"
          redeploy_response=$(curl -s -X POST "$REDEPLOY_URL")
          echo "Redeploy response:"
          echo "$redeploy_response"
          if echo "$redeploy_response" | grep -q "Redeployment triggered"; then
            echo "Redeployment triggered detected."
            echo "status=complete" >> $GITHUB_OUTPUT
          else
            echo "Redeployment trigger message not detected."
            echo "status=incomplete" >> $GITHUB_OUTPUT
          fi
        env:
          DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
          
      - name: Wait for redeployment completion
        run: |
          if [ "${{ steps.redeploy.outputs.status }}" = "complete" ]; then
            echo "Redeployment complete based on trigger message."
          else
            echo "Redeployment not complete. Exiting."
            exit 1
          fi 