name: Build and Deploy Frontend

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'RMW-Frontend/**'

jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true && contains(github.head_ref, 'Frontend')
    runs-on: ubuntu-latest
    
    env:
      DOCKER_REGISTRY: steelduck1
      DOCKER_IMAGE: RMW-Frontend
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f RMW-Frontend/requirements.txt ]; then pip install -r RMW-Frontend/requirements.txt; fi
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./RMW-Frontend
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:latest
          
      - name: Trigger redeployment
        run: |
          REDEPLOY_URL="https://deployment-api.avanade-edge.nl/redeploy?api_key=${{ secrets.DEPLOY_API_KEY }}&service=frontend"
          curl -X POST "${REDEPLOY_URL}" 