name: Build and Deploy Backend

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'RMW-Backend/**'
      - '.github/workflows/BuildAndDeploy_Backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.head_ref == 'Backend')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        working-directory: RMW-Backend
        run: |
          pip install -r requirements.txt
          pip install pytest
          
      - name: Run tests
        working-directory: RMW-Backend
        run: pytest Test.py -v
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: steelduck1/rmw-backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=long
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./RMW-Backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Trigger redeploy
        run: |
          echo "Triggering redeploy..."
          REDEPLOY_URL="http://188.166.89.152:8080/redeploy?api_key=${DEPLOY_API_KEY}&service=backend"
          redeploy_response=$(curl -s -X POST "$REDEPLOY_URL")
          echo "Redeploy response:"
          echo "$redeploy_response"
          if echo "$redeploy_response" | grep -q "Redeployment triggered"; then
            echo "Redeployment triggered detected."
            echo "status=complete" >> $GITHUB_OUTPUT
          else
            echo "Redeployment trigger message not detected."
            echo "status=incomplete" >> $GITHUB_OUTPUT
          fi
        env:
          DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
          
      - name: Wait for redeployment completion
        run: |
          if [ "${{ steps.redeploy.outputs.status }}" = "complete" ]; then
            echo "Redeployment complete based on trigger message."
          else
            echo "Redeployment not complete. Exiting."
            exit 1
          fi 