name: Build and Deploy monitoring

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    types: [closed]
    paths:
      - 'RMW-Monitoring/**'
      - '.github/workflows/BuildAndDeploy_Monitoring.yml'

permissions:
  contents: read

jobs:
  build-deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'Monitoring' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: docker
    env:
      REGISTRY: docker.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Deploy Complete Monitoring Stack
        env:
          DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
        run: |
          echo "Triggering complete monitoring stack redeployment..."
          REDEPLOY_URL="http://188.166.89.152:8080/redeploy?api_key=${DEPLOY_API_KEY}&service=monitoring-full"
          
          # Call the redeploy endpoint
          echo "Calling redeploy endpoint..."
          RESPONSE=$(curl -s -X POST "$REDEPLOY_URL")
          echo "Response: $RESPONSE"
          
          # Check if the deployment was successful
          if echo "$RESPONSE" | grep -q "Complete monitoring stack redeployment successful"; then
            echo "✅ Monitoring stack redeployment triggered successfully!"
          else
            echo "❌ Monitoring stack redeployment failed:"
            echo "$RESPONSE"
            exit 1
          fi 